apiVersion: v1
kind: ConfigMap
metadata:
  name: intervention-svc-env
  namespace: bookflow
data:
  INTERVENTION_RDS_HOST: "bookflow-postgres.c5hcctg31h30.ap-northeast-1.rds.amazonaws.com"
  INTERVENTION_RDS_PORT: "5432"
  INTERVENTION_RDS_DB: "bookflow"
  INTERVENTION_RDS_USER: "intervention_svc"
  INTERVENTION_REDIS_HOST: "bookflow-redis.xxpw8f.0001.apne1.cache.amazonaws.com"
  INTERVENTION_REDIS_PORT: "6379"
  INTERVENTION_AUTH_MODE: "mock"
  INTERVENTION_LOG_LEVEL: "INFO"
  INTERVENTION_NOTIFICATION_SVC_URL: "http://notification-svc.bookflow.svc.cluster.local"
  AUTH_MODE: "jwt"
  AUTH_JWT_ISSUER: "bookflow-auth-pod"
  AUTH_JWT_AUDIENCE: "bookflow-services"
