apiVersion: v1
kind: ConfigMap
metadata:
  name: decision-svc-env
  namespace: bookflow
data:
  DECISION_RDS_HOST: "bookflow-postgres.c5hcctg31h30.ap-northeast-1.rds.amazonaws.com"
  DECISION_RDS_PORT: "5432"
  DECISION_RDS_DB: "bookflow"
  DECISION_RDS_USER: "decision_svc"
  DECISION_REDIS_HOST: "bookflow-redis.xxpw8f.0001.apne1.cache.amazonaws.com"
  DECISION_REDIS_PORT: "6379"
  DECISION_NOTIFICATION_SVC_URL: "http://notification-svc.bookflow.svc.cluster.local"
  DECISION_AUTH_MODE: "mock"
  DECISION_LOG_LEVEL: "INFO"
  AUTH_MODE: "jwt"
  AUTH_JWT_ISSUER: "bookflow-auth-pod"
  AUTH_JWT_AUDIENCE: "bookflow-services"
